### ISSUE TITLE
Can anyone run demo.py with current master branch?

### ISSUE THREAD

**Issue by Jingyu6** [facebookresearch/blt#104]
Tried numerous times for running demo.py but failed cuda error. 

**I strictly followed the setup.py and created a new environment. Not a single error reported during the creation and below is the error from running python.py demo.py "A BLT has":** 

```
│ /home/XXX/miniconda3/envs/blt/lib/python3.11/site-packages/torch/nn/attention/flex_attention.py:162 in create_dense_one                                                     │
[rank0]: │                                                                                                                                                                                │
[rank0]: │    159 │   │   index_mask = col_range < kv_num_blocks.unsqueeze(-1)                                                                                                            │
[rank0]: │    160 │   │                                                                                                                                                                   │
[rank0]: │    161 │   │   # We write to one spot "out of bounds"                                                                                                                          │
[rank0]: │ ❱  162 │   │   valid_indices = torch.where(index_mask, kv_indices, num_cols)                                                                                                   │
[rank0]: │    163 │   │                                                                                                                                                                   │
[rank0]: │    164 │   │   # set the values in 'a' to 1 where the indices are valid                                                                                                        │
[rank0]: │    165 │   │   dense_mask[row_indices, valid_indices] = 1                                                                                                                      │
[rank0]: │                                                                                                                                                                                │
[rank0]: │ ╭────────────────────────────────────────────────────────────────────────────────── locals ────────────────────────────────────────────────────────────────────────────
 ─────╮ │
[rank0]: │ │     col_range = <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below │ │
[rank0]: │ │                 might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>        │ │
[rank0]: │ │    dense_mask = <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below │ │
[rank0]: │ │                 might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>        │ │
[rank0]: │ │        device = device(type='cuda', index=0)                                                                                                                               │ │
[rank0]: │ │    index_mask = <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below │ │
[rank0]: │ │                 might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>        │ │
[rank0]: │ │    kv_indices = <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below │ │
[rank0]: │ │                 might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>        │ │
[rank0]: │ │ kv_num_blocks = <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below │ │
[rank0]: │ │                 might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>        │ │
[rank0]: │ │      num_cols = 1                                                                                                                                                          │ │
[rank0]: │ │      num_rows = 1                                                                                                                                                          │ │
[rank0]: │ │   row_indices = <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below │ │
[rank0]: │ │                 might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>        │ │
[rank0]: │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ─────╯ │
[rank0]: │                                                                                                                                                                                │
[rank0]: │ /home/XXX/miniconda3/envs/blt/lib/python3.11/site-packages/torch/_higher_order_ops/flex_attention.py:85 in __torch_function__                                               │
[rank0]: │                                                                                                                                                                                │
[rank0]: │     82 │   │   │   index_args = pytree.tree_leaves(args[1])                                                                                                                    │
[rank0]: │     83 │   │   │   if all(isinstance(x, torch.Tensor) for x in index_args):                                                                                                    │
[rank0]: │     84 │   │   │   │   return torch.ops.aten.index(args[0], index_args)                                                                                                        │
[rank0]: │ ❱   85 │   │   return func(*args, **(kwargs or {}))                                                                                                                            │
[rank0]: │     86                                                                                                                                                                         │
[rank0]: │     87                                                                                                                                                                         │
[rank0]: │     88 class FlexAttentionHOP(HigherOrderOperator):                                                                                                                            │
[rank0]: │                                                                                                                                                                                │
[rank0]: │ ╭────────────────────────────────────────────────────────────────────────────────── locals ────────────────────────────────────────────────────────────────────────────
 ─────╮ │
[rank0]: │ │   args = (                                                                                                                                                                 │ │
[rank0]: │ │          │   <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below    │ │
[rank0]: │ │          might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>,              │ │
[rank0]: │ │          │   <repr-error 'CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below    │ │
[rank0]: │ │          might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'>,              │ │
[rank0]: │ │          │   1                                                                                                                                                             │ │
[rank0]: │ │          )                                                                                                                                                                 │ │
[rank0]: │ │   func = <built-in method where of type object at 0x7f09c805f240>                                                                                                          │ │
[rank0]: │ │ kwargs = None                                                                                                                                                              │ │
[rank0]: │ │   self = <torch._higher_order_ops.flex_attention.TransformGetItemToIndex object at 0x7f059437f390>                                                                         │ │
[rank0]: │ │  types = ()                                                                                                                                                                │ │
[rank0]: │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ─────╯ │
[rank0]: ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ───────╯
[rank0]: RuntimeError: CUDA error: device-side assert triggered
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Aborted (core dumped)
```

**CUDA info:**
```
Tue Apr 29 23:13:15 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:19:00.0 Off |                    0 |
| N/A   31C    P0             78W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          Off |   00000000:2D:00.0 Off |                    0 |
| N/A   31C    P0             73W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          Off |   00000000:3F:00.0 Off |                    0 |
| N/A   32C    P0             70W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          Off |   00000000:66:00.0 Off |                    0 |
| N/A   30C    P0             71W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          Off |   00000000:9B:00.0 Off |                    0 |
| N/A   29C    P0             72W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          Off |   00000000:AE:00.0 Off |                    0 |
| N/A   31C    P0             75W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          Off |   00000000:BF:00.0 Off |                    0 |
| N/A   31C    P0             72W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          Off |   00000000:E4:00.0 Off |                    0 |
| N/A   30C    P0             71W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

Could someone from the team confirm that the master branch is working and there's no updates on dependencies? Or maybe let us know a specific commit that works by running the guidance in README.md. Appreciate it a lot!

**Comment by Jingyu6** [comment]
Maybe theres some mismatch on torch version and its the flex attn that gives errror. Could you share the specific version of torch u guys have tested with?

**Comment by EntilZha** [comment]
Sorry about lack of updates here, I've been busy with adding HF integration, but I've also been looking into how we can create a vanilla Dockerfile. Making progress on that, just takes a little bit more work.

This is what we have for a working conda env https://gist.github.com/EntilZha/a70177a6a3d6fb3db0d04d79b9e5d48f, I saw that at least the xformers spec is different. It is entirely possible that the env specs here diverged from what we have internally since the ones here are based on lingua and we often avoid creating new envs and instead pack/unpack them internally.

**Comment by EntilZha** [comment]
@Jingyu6, could you try running these steps manually? I tried these and it worked. If it fixes things for you I can update the docs.
```
conda create -n blt python=3.12
conda activate blt
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121
pip install ninja
pip install -v -U git+https://github.com/facebookresearch/xformers.git@de742ec3d64bd83b1184cc043e541f15d270c148
pip install -r requirements.txt
```

**Comment by EntilZha** [comment]
That's great! I'll leave this issue open for a little more then close, since I have updated instructions here https://github.com/facebookresearch/blt/pull/105

**Comment by Jingyu6** [comment]
Thanks a lot @EntilZha! This is awesome and works fine on H100s as I tested. 

Could you provide some guidance on using kv cache for generation? Another question is: do we have an instruct BLT model?

**Comment by Jingyu6** [comment]
Also wanted to make sure if the results are expected for blt-1b:

Example 1
```
Prompt: "A BLT has" Completion: " a bacon, lettuce and tomato sandwich. A BLT is also a song by the Beatles. A BLT is also a song by the Beach Boys. A BLT is also a song by the Beatles. A BLT is also a song by the Beatles. A BLT is also a song by the Beatles. A BLT is also a song by the B"
```

Example 2
```
Prompt: "Who is Magnus Carlsen? " Completion: "Why is he so good?

Who is Magnus Carlsen? Why is he so good?

Who is Magnus Carlsen? Why is he so good?

The best answer to any question.
June 1 2012 10:58 AM

Who Is Magnus Carlsen? Why Is He So Good?

Magnus Carlsen.
Magnus Carlsen is the world's best c"
```

Was wondering if you guys could share some scripts to reproduce results on tasks like Arc-C and HumanEval?

**Comment by EntilZha** [comment]
That output looks correct and is what I get with the weights/all default args.

It will be a bit harder to share the exact scripts/evals for those tasks since we used an internal eval framework for experiments that I wouldn't anticipate being open sourced. That said, I put some initial work into making the BLT work with the llm eval library that lingua used in their code, but it will take more work to get functional for BLT-like models. If you're interested, the code for that is in `bytelatent/eval.py`.

If my memory is right, it works for regular transformers (ie, i tested it with the entropy model), but would need to make the preprocessing for the BLT model work. There may have also been an issue I didn't resolve with parallelism and aggregating values.

**Comment by SathvikSat** [comment]
@EntilZha  I always get the following output for "A BLT has" sample. Is this an expected behaviour with blt-1b, default args:

> Prompt: "A BLT has" Completion: " a bacon, lettuce and tomato sandwich. A BLT is also a slang term for a blonde who is a lesbian trapped in a man's body. A BLT is also a slang term for a blonde who is a lesbian trapped in a man's body. A BLT is also a slang term for a blonde who is a lesb"

I am using A100, 80GB.

**Comment by EntilZha** [comment]
This is what I get on our side:
```
Prompt: "A BLT has"
Completion: " a bacon, lettuce and tomato sandwich. A BLT is also a song by the Beatles. A BLT is also a song by the Beach Boys. A BLT is also a song by the Beatles. A BLT is also a song by the Beatles. A BLT is also a song by the Beatles. A BLT is also a song by the B"
```
I'd also expect the output to not change since the seed is set to the same thing every script call.

**Comment by bc-li** [comment]
> Thanks a lot [@EntilZha](https://github.com/EntilZha)! This is awesome and works fine on H100s as I tested.
> 
> Could you provide some guidance on using kv cache for generation? Another question is: do we have an instruct BLT model?

I also have the question about KVCache, it looks like the current code doesn't add KVCache support to BLT for inference? (from what I saw in `bytelatent/generate_blt.py`)

**Comment by EntilZha** [comment]
@bc-li, correct, we don't have KVCache implemented, in part because of time constraint and in part since I think the implementation is a bit tricky to get right due to the local/global/patching parts of the model. We'd welcome contributions on this, but may eventually add it ourselves.

If you are interested in discussing further, let's make another issue since the main problem in this issue seems resolved.
